import { DeployStateRequest } from '../generated/graphql'

const environmentConfiguration: DeployStateRequest[] = [
  {
    displayOrder: 1,
    displayName: 'Test Slot 1',
    releaseEnvironmentName: 'New Test01 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 260,
    artifactAlias: '[TestSlot] CloudApp',
    // pipelineName: 'New Test01 CI'
    // artifactFilter: 'Test'
  },
  {
    displayOrder: 2,
    displayName: 'Test Slot 2',
    releaseEnvironmentName: 'New Test02 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 266,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 3,
    displayName: 'Test Slot 3',
    releaseEnvironmentName: 'New Test03 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 267,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 4,
    displayName: 'Test Slot 4',
    releaseEnvironmentName: 'New Test04 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 273,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 5,
    displayName: 'Test Slot 5',
    releaseEnvironmentName: 'New Test05 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 268,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 6,
    displayName: 'Test Slot 6',
    releaseEnvironmentName: 'New Test06 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 269,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 7,
    displayName: 'Test Slot 7',
    releaseEnvironmentName: 'New Test07 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 270,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 8,
    displayName: 'Test Slot 8',
    releaseEnvironmentName: 'New Test08 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 271,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 9,
    displayName: 'Test Slot 9',
    releaseEnvironmentName: 'New Test09 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 272,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 10,
    displayName: 'Test Slot 10',
    releaseEnvironmentName: 'New Test10 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 274,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 11,
    displayName: 'Test Slot 11',
    releaseEnvironmentName: 'New Test11 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 275,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 12,
    displayName: 'Test Slot 12',
    releaseEnvironmentName: 'New Test12 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 276,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 13,
    displayName: 'Test Slot 13',
    releaseEnvironmentName: 'New Test13 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 277,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 14,
    displayName: 'Test Slot 14',
    releaseEnvironmentName: 'New Test14 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 276,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 15,
    displayName: 'Test Slot 15',
    releaseEnvironmentName: 'New Test15 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 279,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 16,
    displayName: 'Test Slot 16',
    releaseEnvironmentName: 'New Test16 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 280,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 17,
    displayName: 'Test Slot 17',
    releaseEnvironmentName: 'New Test17 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 281,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 18,
    displayName: 'Test Slot 18',
    releaseEnvironmentName: 'New Test18 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 282,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 19,
    displayName: 'Test Slot 19',
    releaseEnvironmentName: 'New Test19 CI',
    releaseDefinitionId: 21,
    definitionEnvironmentId: 283,
    artifactAlias: '[TestSlot] CloudApp',
  },
  {
    displayOrder: 20,
    displayName: 'Staging',
    releaseEnvironmentName: 'New Staging',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 250,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
  {
    displayOrder: 21,
    displayName: 'Web1',
    releaseEnvironmentName: '@pr-auea-web01',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 140,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
  {
    displayOrder: 22,
    displayName: 'Web2',
    releaseEnvironmentName: '@pr-auea-web02',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 141,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
  {
    displayOrder: 23,
    displayName: 'Web3',
    releaseEnvironmentName: '@pr-auea-web03',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 142,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
  {
    displayOrder: 24,
    displayName: 'Web4',
    releaseEnvironmentName: '@pr-auea-web04',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 143,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
  {
    displayOrder: 25,
    displayName: 'Web5',
    releaseEnvironmentName: '@pr-auea-web05',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 106,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
  {
    displayOrder: 26,
    displayName: 'Job1',
    releaseEnvironmentName: '@pr-auea-job01',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 164,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
  {
    displayOrder: 27,
    displayName: 'Job2',
    releaseEnvironmentName: '@pr-auea-job02',
    releaseDefinitionId: 16,
    definitionEnvironmentId: 165,
    artifactAlias: '[ALPHA] Continuous Build & Packaging CloudApp',
  },
]

export default environmentConfiguration
